// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epvrktapeqeivkfxuqdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwdnJrdGFwZXFlaXZrZnh1cWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTMxMTgsImV4cCI6MjA3MjE4OTExOH0._ye_75zTczqF-ST5B_oHGt2XnR4ZCqmGskMaB8HOUEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});